# Generated by Django 5.1 on 2024-10-01 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Имя рецепта:')),
                ('description', models.CharField(max_length=2000, verbose_name='Как готовить:')),
                ('preparation_steps', models.TextField(verbose_name='Из чего готовим:')),
                ('preparation_time', models.IntegerField(blank=True, verbose_name='Сколько мин.:')),
                ('data', models.DateField(auto_now_add=True, verbose_name='Дата добавления:')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='img/', verbose_name='Фото:')),
                ('autor', models.ForeignKey(default='folk_recipe', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('category', models.ForeignKey(blank=True, default='no_category', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='нет', to='recipeapp.categories', verbose_name='Категория:')),
            ],
        ),
    ]
